str = "abc \t 123 Ex   {name} {value} aaa"
print(str.capitalize())
print(str.center(50, '='))
print(str.count("a"))
print(str.encode())
print(str.endswith("a"))
print(str.expandtabs(tabsize=16))
print(str.format(name='thomas', value="1"))
print(str.find('a'))
print(str.format_map({"name": "value", "value": "1"}))
print(str.index('a'))
print(str.isalnum())
print("1".isalpha())
print("az1".isdecimal())
print("1".isdigit())
print("aaaA".islower())
print(" ".isspace())
print("Aaaa".isupper())
print("1".isnumeric())
print(','.join(["1", "2", "3"]))
print("111".ljust(10), 'a')
print("e".rjust(10))
print("A".lower())
print('a', "bbbba".lstrip('bbb'))
print('abbbbbbbbb'.maketrans("abcdef", '123456'))
p = 'abbbbbbbbb'.maketrans("abcdef", '123456');
print("abcdef".translate(p))
# print('aaa'.partition('a'))
